google_analytics: G-JGZRXWFK8F

title: Not Shant Blog
description: Personal Blog of Prashant Mittal

plugins:
  - jekyll-seo-tag

exclude: [
  styles/index.css,
  styles/syntax.css,
  package.json,
  package-lock.json,
  postcss.config.js,
  readme.md,
]
