google_analytics: G-JGZRXWFK8F

title: Not Shant Blog
description: Personal Blog of Prashant Mittal
url: https://notshant.xyz
twitter:
  username: prashant_mit
  card: summary_large_image

defaults:
  - scope:
      path: "assets/estimates/deck.html"
    values:
      sitemap: false

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude: [
  styles/index.css,
  styles/syntax.css,
  package.json,
  package-lock.json,
  postcss.config.js,
  readme.md,
]
